<?php

namespace Gites\GitesBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * GitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GitesRepository extends \Doctrine\ORM\EntityRepository
{

}
