<?php

namespace Gites\GitesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends EntityRepository
{
    public function myFindAll()
    {

        $qb = $this->createQueryBuilder('a');
        $qb->orderBy('a.gite', 'ASC')
            ->orderBy('a.ordre', 'ASC');
        return $qb
            ->getQuery()
            ->getResult();
    }
}
