<?php

namespace Gites\GitesBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * SlidesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlidesRepository extends EntityRepository
{
    public function myFindAll()
    {

        $qb = $this->createQueryBuilder('a');
        $qb->orderBy('a.ordre', 'ASC') ;
        return $qb
            ->getQuery()
            ->getResult();
    }
    public function myFindAllVisible($genre)
    {


        $qb = $this->createQueryBuilder('a');
        $qb ->where('a.dateParutionDebut <= :aujourdhui')
            ->andWhere('a.dateParutionFin >= :aujourdhui')
            ->andWhere('a.genre = :genre')
            ->orderBy('a.ordre', 'ASC')
            ->setParameter('aujourdhui',  new \DateTime(), \Doctrine\DBAL\Types\Type::DATETIME)
            ->setParameter('genre', $genre);

        return $qb
            ->getQuery()
            ->getResult();
    }
}
