home:
    pattern:  /
    defaults: { _controller: GitesBundle:Gites:index }

admin:
    pattern:  admin/
    defaults: { _controller: GitesBundle:GitesAdmin:index }

contact:
    pattern:  contact/
    defaults: { _controller: GitesBundle:Gites:contact}

gite:
    pattern:  Gites_66/{slug}
    defaults: { _controller: GitesBundle:Gites:detail}

